Repository apple/swift-http-types, pull requests merged in 2024-11, with the labels that each got.

#71 Support building without CoreFoundation on Windows
  Sources/HTTPTypesFoundation/HTTPRequest+URL.swift
  Tests/HTTPTypesFoundationTests/HTTPTypesFoundationTests.swift
Labels: semver/patch, platform/windows

#70 Adopt Mutex where available
  Benchmarks/Thresholds/6.0/Benchmarks.HTTPFields.init(dictionaryLiteral).p90.json
  Benchmarks/Thresholds/nightly-6.0/Benchmarks.HTTPFields.init(dictionaryLiteral).p90.json
  Benchmarks/Thresholds/nightly-main/Benchmarks.HTTPFields.init(dictionaryLiteral).p90.json
  Sources/HTTPTypes/HTTPFields.swift
Labels: semver/patch, area/performance

#72 Remove usable from inline and internal properties
  Sources/HTTPTypes/HTTPFieldName.swift
  Sources/HTTPTypes/NIOLock.swift
Labels: semver/none

#73 add .editorconfig file
  .editorconfig
Labels: semver/none

#75 Aligning semantic version label check name
  .github/workflows/pull_request_label.yml
Labels: semver/none
